local A_2 = game.PlaceId
local A_1 = game.JobId

--game.Players.LocalPlayer:Kick("Unable to find server, OMV. Error code: 2913 \n\nScript service down or not avaliable. Please contact to michi2200_#1674")
--game.Players.LocalPlayer:Kick("Unable to find the bypasser. Error code: 271 \n\nBypasser is not online or not avaliable. Please contact to michi2200_#1674")
--game.Players.LocalPlayer:Kick("Update is released. Waiting to taking action to access to the script to everyone. \n\nError code: 273")
--game.Players.LocalPlayer:Kick("Data base is down. We will fix it. \n\nError code: 274")
--game.Players.LocalPlayer:Kick("Unable to find path to execute. \n\nError code: 275")
--game.Players.LocalPlayer:Kick("A_1,A_2 VAR cannot be founded in the script. Bypassers are locked. \n\nError code: 276")
--game.Players.LocalPlayer:Kick("USER NOT IDENTIFIED. Use a real account. \n\nError code: 281")
--game.Players.LocalPlayer:Kick("Data breach is ongoing. Cannot find any script right now. Be back soon \n\nError code: 282")
--game.Players.LocalPlayer:Kick("getstring not able do find. \n\nError code: 283")
--game.Players.LocalPlayer:Kick("CODE NOT IDENTIFIED. Use a vpn. \n\nError code: 300")
--game.Players.LocalPlayer:Kick(""A_1" \n\nError code: 310")
--game.Players.LocalPlayer:Kick("A_3,A_4 VAR cannot be founded in the script. Bypassers are locked. \n\nError code: 276")
--game.Players.LocalPlayer:Kick("A_5,A_6 VAR cannot be founded in the script. Bypassers are locked. \n\nError code: 276")
game.Players.LocalPlayer:Kick("landOs-ERROR CHECK CONSOLE.")
rconsoleerr("landOs DB is not ONLINE cannot log this script. Check for updates. PSVKS")
rconsolewarn("landOs sLoad() function not avaliable. ERR to load : LINE 67 pathway: gateway:22")
rconsoleerr("NARCU Version- VALID.user.Check.Exec line 5 CANNOT execute cause (var not found.)")
rconsoleprint("Contact michi")
